agents:
    - antigravity
skills:
    - file://../skills/skills/git
    - file://../skills/skills/cli
    - file://../skills/skills/documentation
    - file://../skills/skills/instrumentation
    - file://../skills/skills/configuration
    - file://../skills/skills/go
    - file://../skills/skills/taskfile
    - file://../skills/skills/architecture
    - file://../skills/skills/rpc
    - file://../skills/skills/dependency_injection
