version: '3'

tasks:
  setup:
    desc: Installs required tools and dependencies
    cmds:
      - go mod download
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  generate:
    desc: Generates code as required
    cmds:
      - go generate ./...

  build:
    desc: Compiles the application binary
    cmds:
      - go build -o bin/idx .

  test:
    desc: Runs unit tests
    cmds:
      - go test -race ./...

  lint:
    desc: Runs code linters
    cmds:
      - golangci-lint run

  validate:
    desc: Runs lints, unit tests, smoke tests, and the build
    cmds:
      - task: lint
      - task: test
      - task: build
